---
title: "Human_Ovarian_Cancer"
output: html_document
date: "2025-04-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("./0_functions.R")
```

```{r}
library(quantiseqr)
library(CARDspa)
#library(zellkonverter)
```

## R Markdown
```{r}
library(ExperimentHub)
library(DropletUtils)
library(TENxVisiumData)
eh <- ExperimentHub()
(q <- query(eh, "TENxVisium"))
```


```{r}
# Specific for the error in the package version 1.38.1
setClassUnion("ExpData", c("matrix", "SummarizedExperiment"))
```

# Human Ovarian Cancer
```{r}
spe_complete <- HumanOvarianCancer()
rownames(spe_complete)= rowData(spe_complete)$symbol


#WTA
#spe=spe_complete[,sample(ncol(spe_complete), 200)]
spe_assay=assay(spe_complete) %>% as.matrix()
wta=spe_assay[complete.cases(spe_assay),]


#Targeted Immunology
targeted_immunology_ele<- swapAltExp(spe_complete,"TargetedImmunology", saved = NULL)
rownames(targeted_immunology_ele) <- rowData(targeted_immunology_ele)$symbol
targeted_immunology_assay=assay(targeted_immunology_ele) %>% as.matrix()




# Targeted Pan Cancer
targeted_pan_cancer_ele<- swapAltExp(spe_complete,"TargetedPanCancer", saved = NULL)
rownames(targeted_pan_cancer_ele) <- rowData(targeted_pan_cancer_ele)$symbol
targeted_pan_cancer_assay=assay(targeted_pan_cancer_ele) %>% as.matrix()

```


```{r}
# Saving the matrices as anndata objects
# Complete WTA
library(Matrix)
writeMM(counts(spe_complete), "../intermediate_data/Human_ovarian_cancer/wta_counts.mtx")
writeLines(rownames(spe_complete), "../intermediate_data/Human_ovarian_cancer/wta_genes.txt")
writeLines(colnames(spe_complete), "../intermediate_data/Human_ovarian_cancer/wta_barcodes.txt")
write_delim(spatialCoords(spe_complete) %>% as.data.frame() %>% rownames_to_column(var="barcode"), "../intermediate_data/Human_ovarian_cancer/wta_spatial_coords.csv",delim = ",")


# Targeted pan Cancer
writeMM(counts(targeted_pan_cancer_ele), "../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer_counts.mtx")
writeLines(rownames(targeted_pan_cancer_ele), "../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer_genes.txt")
writeLines(colnames(targeted_pan_cancer_ele), "../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer_barcodes.txt")


# Targeted immunology
writeMM(counts(targeted_immunology_ele), "../intermediate_data/Human_ovarian_cancer/targeted_immunology_counts.mtx")
writeLines(rownames(targeted_immunology_ele), "../intermediate_data/Human_ovarian_cancer/targeted_immunology_genes.txt")
writeLines(colnames(targeted_immunology_ele), "../intermediate_data/Human_ovarian_cancer/targeted_immunology_barcodes.txt")


```

```{r}
deconvolute_real_data=function(mat,bg)
{
  
# TPM like normalisaion
mat_tpm_like= apply(mat, 2, function(x) x * 1000000 / sum(x))

mat_tpm_like=mat[, !apply(mat_tpm_like, 2, anyNA)]
mat <- mat[, colSums(mat_tpm_like) != 0]


# Calculate Q3 for each column
# q3_values <- apply(mat, 2, function(x) quantile(x, 0.75))
# q3_geometric_mean=exp(mean(log(q3_values)))
# mat_q3_norm= sweep(mat, 2, q3_values, FUN = "/") * q3_geometric_mean


quntiseq_res <- deconvolute(mat_tpm_like, "quantiseq",tumor = TRUE) %>% 
                mutate(cell_type= ifelse(grepl("T cell",cell_type)==TRUE,"T cell",cell_type)) %>% 
                dplyr::group_by(cell_type) %>% 
                dplyr::summarise_if(is.numeric, sum) %>% 
                pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                mutate(Deconvolution_type="quanTIseq")


 mcp_counter_res <- deconvolute(mat_tpm_like, "mcp_counter",tumor = TRUE) %>% 
                    mutate(across(contains("E_"), ~./sum(.))) %>% 
                    mutate(cell_type= ifelse(grepl("T cell",cell_type)==TRUE,"T cell",cell_type)) %>% 
                    dplyr::group_by(cell_type) %>% 
                    dplyr::summarise_if(is.numeric, sum) %>% 
                    pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                    mutate(Deconvolution_type="MCPcounter")

     epic_res <- tryCatch({
      deconvolute(mat_tpm_like, "epic", tumor = TRUE) %>%
        mutate(cell_type = ifelse(grepl("T cell", cell_type) == TRUE, "T cell", cell_type)) %>%
        dplyr::group_by(cell_type) %>%
        dplyr::summarise_if(is.numeric, sum) %>%
        pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>%
        mutate(Deconvolution_type = "EPIC")
    }, error = function(e) {
      message("EPIC Failed to run: ", e$message)
      return(NULL) # Return NULL or an alternative value to handle the error
    })
 
 spatial_decon_result= spatialdecon(mat_tpm_like,
                                 bg = bg,
                                 X = safeTME)

spatial_decon_res=as.data.frame(spatial_decon_result$prop_of_all) %>% 
                     rownames_to_column(var="cell_type") %>% 
                     mutate(cell_type= ifelse(grepl("^T",cell_type)==TRUE,"T cell",cell_type)) %>%
                     mutate(cell_type= ifelse(grepl("^B.",cell_type)==TRUE,"B cell",cell_type)) %>% 
                     mutate(cell_type= ifelse(grepl("macrophages",cell_type)==TRUE,"Macrophage",cell_type)) %>% 
                     dplyr::group_by(cell_type) %>% 
                     dplyr::summarise_if(is.numeric, sum) %>% 
                     pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                     mutate(Deconvolution_type="SpatialDecon \ndefault signature")

  res_df= rbind(quntiseq_res,if (!is.null(epic_res)) epic_res,mcp_counter_res,spatial_decon_res) %>% 
          mutate(cell_type = case_when(
          cell_type %in% c("Macrophage M1", "Macrophage M2") ~ "Macrophage",
          cell_type %in% c("monocytes.C", "monocytes.NC.I") ~ "Monocyte",
          cell_type == "NK" ~ "NK cell",
          cell_type == "endothelial.cells" ~ "Endothelial cell",
          cell_type == "fibroblasts" ~ "Fibroblast cell",
          cell_type %in% c("mDCs", "pDCs") ~ "Dendritic cell",
          cell_type == "mast" ~ "Mast cell",
          cell_type == "plasma" ~ "Plasma cell",
          cell_type == "neutrophils" ~ "Neutrophil",
          TRUE ~ cell_type )) %>% 
            dplyr::group_by(Deconvolution_type,Sample_name,cell_type) %>% 
                     dplyr::summarise_if(is.numeric, sum)
  return(res_df)
}
```


```{r}
wta_res= deconvolute_real_data(wta,0.01) %>% mutate(Gene_panel="WTA")
targeted_immunoly_res=deconvolute_real_data(targeted_immunology_assay,0.01) %>% mutate(Gene_panel="Targeted Immunology")
targeted_pan_cancer_res=deconvolute_real_data(targeted_pan_cancer_assay,0.01) %>% mutate(Gene_panel="Targeted Pan Cancer")
```


```{r}
saveRDS(wta_res, file = "../intermediate_data/Human_ovarian_cancer/wta_deconvolution.RDS")
saveRDS(targeted_immunoly_res, file = "../intermediate_data/Human_ovarian_cancer/targeted_immunology_deconvolution.RDS")
saveRDS(targeted_pan_cancer, file = "../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer.RDS")
```

# Plotting
```{r}
wta_res=readRDS("../intermediate_data/Human_ovarian_cancer/wta_deconvolution.RDS")
targeted_immunoly_res=readRDS("../intermediate_data/Human_ovarian_cancer/targeted_immunology_deconvolution.RDS")
targeted_pan_cancer=readRDS("../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer.RDS")
```


# Adding more deconvolution methods (SPOTLight, CARD, RCTD, Cell2location)
```{r}
#  sce_h5ad <- system.file(
#      "extdata", "../Data/ovarian_cancer_scRNAseq/921d46a3-69b4-44a8-b2d6-9ef5c7803bc3.h5ad",
#      package = "zellkonverter"
#  )
# 
# sce <- readH5AD("../Data/ovarian_cancer_scRNAseq/921d46a3-69b4-44a8-b2d6-9ef5c7803bc3.h5ad")
# sce_sub=sce[,colData(sce)$assay=="10x 3' v2" & colData(sce)$disease=='ovarian cancer']
# assayNames(sce_sub)[1] <- "counts"
# logcounts(sce_sub) <- log1p(counts(sce_sub))
# rownames(sce_sub)=rowData(sce)$feature_name
# saveRDS(sce_sub, file = "../Data/ovarian_cancer_scRNAseq/ovarian_cancer_subset.RDS")
```

```{r}
# Creating the deconvolution function
sce= readRDS("../Data/ovarian_cancer_scRNAseq/ovarian_cancer_subset.RDS")
rownames(sce) <- make.unique(rownames(sce))

spatial_coords=spatialCoords(spe_complete) %>% as.data.frame() %>% setNames(c("x", "y"))



spatial_data_matrix=wta

spl_rctd_card_deconvolution <- function(sce,spatial_data_matrix,spatial_coords,gene_panel)
{
# Spotlight
spl_res = spotlight_decon(spatial_data_NS = spatial_data_matrix %>% as.data.frame() %>% rownames_to_column(var="HUGO"),
                          sce_NS = sce, 
                          mean_auc_cutoff=0.7) %>% 
         pivot_longer(cols = -cell_type, names_to = "Sample_name", 
                       values_to = "Deconvolution_proportions") %>% 
          mutate(Deconvolution_type="SPOTlight")

# RCTD
# It require interger counts for sce, so i round the sce data to nearest integer
colData(sce)$Barcode=colnames(sce)
sce_mod=sce
assay(sce_mod, "counts") <- round(assay(sce_mod, "counts"))
rctd_res=rctd_decon(spatial_data_matrix %>% as.data.frame() %>% rownames_to_column(var="HUGO"), 
                    sce_mod) %>% 
        pivot_longer(cols = -cell_type, names_to = "Sample_name", 
                       values_to = "Deconvolution_proportions") %>% 
          mutate(Deconvolution_type="RCTD")

# CARD
rownames(spatial_data_matrix) <- make.unique(rownames(spatial_data_matrix))
set.seed(seed = 20200107)
CARD_obj <- CARD_deconvolution(
    sc_count = counts(sce),
    sc_meta = colData(sce) %>% as.data.frame() %>% select(cell,donor_id),
    spatial_count =spatial_data_matrix ,
    spatial_location = spatial_coords,
    ct_varname = "cell",
    ct_select = NULL,
    sample_varname = "donor_id",
    mincountgene = 10,
    mincountspot = 500
)

card_res=t(CARD_obj$Proportion_CARD) %>% 
         as.data.frame() %>% 
         rownames_to_column(var="cell_type") %>% 
          pivot_longer(cols = -cell_type, names_to = "Sample_name", 
                       values_to = "Deconvolution_proportions") %>% 
          mutate(Deconvolution_type="CARD")

spl_rctd_card_res= rbind(spl_res,rctd_res,card_res) %>% 
                   mutate(Gene_panel= gene_panel)

saveRDS(spl_rctd_card_res, file = paste0("../intermediate_data/Human_ovarian_cancer/",gene_panel,"_deconvolution_spl_rctd_card.RDS"))
return(spl_rctd_card_res)
}
         
wta_new_res= spl_rctd_card_deconvolution(sce,wta,spatial_coords,"WTA")
targeted_pan_cancer_new_res= spl_rctd_card_deconvolution(sce,targeted_pan_cancer_assay,spatial_coords,"Targeted Pan Cancer")
targeted_immunology_new_res= spl_rctd_card_deconvolution(sce,targeted_immunology_assay,spatial_coords,"Targeted Immunology")

```

### For figures- start here
```{r}
# Reading cell2location results
cell2loc_pan_cancer= read_csv("../intermediate_data/cell2location_res/cell2location_map/cell2location_map/ovarian_targeted_pan_cancer_res.csv" ) %>% 
  dplyr::select(-"...1") %>% 
  dplyr::rename("Gene_panel"="parameter") %>% 
  dplyr::mutate(Gene_panel="Targeted Pan Cancer") %>% 
   pivot_longer(cols = -c(cell_type,Gene_panel), names_to = "Sample_name", 
                       values_to = "Deconvolution_proportions") %>% 
          mutate(Deconvolution_type="cell2location")

  
cell2loc_immuno=read_csv("../intermediate_data/cell2location_res/cell2location_map/cell2location_map/ovarian_targeted_immunology_res.csv")%>%
  dplyr::select(-"...1") %>% 
  dplyr::rename("Gene_panel"="parameter") %>% 
   dplyr::mutate(Gene_panel="Targeted Immunology") %>% 
   pivot_longer(cols = -c(cell_type,Gene_panel), names_to = "Sample_name", 
                       values_to = "Deconvolution_proportions") %>% 
          mutate(Deconvolution_type="cell2location")

cell2loc_wta= read_csv("../intermediate_data/cell2location_res/cell2location_map/cell2location_map/ovarian_cancer_wta_res.csv") %>%
  dplyr::select(-"...1") %>%
  dplyr::rename("Gene_panel"="parameter") %>%
  dplyr::mutate(Gene_panel="WTA") %>%
   pivot_longer(cols = -c(cell_type,Gene_panel), names_to = "Sample_name",
                       values_to = "Deconvolution_proportions") %>%
          mutate(Deconvolution_type="cell2location")


```
```{r}
 res=rbind(readRDS("../intermediate_data/Human_ovarian_cancer/wta_deconvolution.RDS"),
      readRDS("../intermediate_data/Human_ovarian_cancer/targeted_immunology_deconvolution.RDS"),
      readRDS("../intermediate_data/Human_ovarian_cancer/targeted_pan_cancer.RDS"),
      readRDS("../intermediate_data/Human_ovarian_cancer/WTA_deconvolution_spl_rctd_card.RDS"),
      readRDS("../intermediate_data/Human_ovarian_cancer/Targeted Immunology_deconvolution_spl_rctd_card.RDS"),
      readRDS("../intermediate_data/Human_ovarian_cancer/Targeted Pan Cancer_deconvolution_spl_rctd_card.RDS"),
      cell2loc_wta,
      cell2loc_pan_cancer,
      cell2loc_immuno
      )


# unique(res$Deconvolution_type)
# 
# res %>% group_by(Sample_name) %>% filter(n() >= 24)
```


```{r}

set.seed(5286)
selected_barcodes=sample(unique(res$Sample_name),500)
```

```{r}
res %>% 
  filter(Deconvolution_type=="EPIC") %>% 
  filter(Sample_name %in% selected_barcodes ) %>% 
  pull(Sample_name) %>% 
  unique() %>% 
  length()

res %>% 
  filter(Deconvolution_type=="quanTIseq") %>% 
  filter(Sample_name %in% selected_barcodes ) %>% 
  pull(Sample_name) %>% 
  unique() %>% 
  length()

res %>% 
  filter(Deconvolution_type=="RCTD") %>% 
  filter(Sample_name %in% selected_barcodes ) %>% 
  pull(Sample_name) %>% 
  unique() %>% 
  length()

```


```{r}
res_for_plots=res %>% 
  dplyr::filter(Sample_name %in% selected_barcodes ) %>% 
  dplyr::filter(Deconvolution_type !="MCPcounter") %>% 
  dplyr::filter(cell_type %in% c("B cell","T cell") ) %>% 
  dplyr::mutate(Deconvolution_type=ifelse(Deconvolution_type=="SpatialDecon \ndefault signature","SpatialDecon",Deconvolution_type)) %>% 
  dplyr::mutate(Gene_panel=ifelse(Gene_panel=="Targeted Pan Cancer","Targeted Pan-Cancer",Gene_panel)) %>% 
  dplyr::mutate(Deconvolution_type=factor(Deconvolution_type,levels = c("quanTIseq","EPIC","SPOTlight","SpatialDecon","CARD","RCTD","cell2location"))) %>% 
  dplyr::mutate(Gene_panel=factor(Gene_panel,levels=c("WTA","Targeted Pan-Cancer","Targeted Immunology"))) %>% 
  dplyr:: mutate(Gene_panel = fct_recode(Gene_panel,"10x Visium \nWTA Probe-set" = "WTA"))
```


```{r}

# Pivot to wide format for Friedman test
 friedman_input <- res_for_plots %>%
   select(Sample_name, Gene_panel, Deconvolution_proportions, cell_type) %>%
   pivot_wider(names_from = Gene_panel, values_from = Deconvolution_proportions)
 

methods <- levels(res_for_plots$Deconvolution_type)

all_p_values= data.frame()

# Loop through each Deconvolution_type
for (cell in c("B cell","T cell")) 
   {
       for (method in methods) {
       cat("\n---", method, "---\n")
       
       # Subset one method
       df_sub <- friedman_input %>%
         filter(cell_type==cell) %>% 
         filter(Deconvolution_type == method) %>%
         select(Sample_name, `10x Visium \nWTA Probe-set`, `Targeted Pan-Cancer`, `Targeted Immunology`)
       
       # Friedman test
       friedman_res <- friedman.test(as.matrix(df_sub[,-1]))
       print(friedman_res)
       
       # Reshape to long for pairwise wilcox
       df_long <- df_sub %>%
         ungroup() %>% 
         select(1,3,4,5) %>% 
         pivot_longer(cols = -Deconvolution_type, names_to = "Panel", values_to = "Proportion")
       
       # Pairwise Wilcoxon signed-rank tests (with Bonferroni correction)
       pairwise_res <- df_long %>%
         pairwise_wilcox_test(
           Proportion ~ Panel,
           paired = TRUE,
           p.adjust.method = "bonferroni"
         )
       
       all_p_values=rbind(all_p_values,
                          pairwise_res %>% 
                          mutate("Deconvolution_tool"=method,
                                 "cell_type"=cell))
       }
 }

```

```{r}

plt= res_for_plots %>% 
  ggplot(aes(x=Gene_panel,y=Deconvolution_proportions, color=Gene_panel, group=Sample_name))+
  geom_line(alpha = 0.2, show.legend = FALSE)+
  geom_point()+
  facet_grid(cell_type~Deconvolution_type)+
  scale_color_manual(values= c("10x Visium \nWTA Probe-set"="#26547c","Targeted Immunology"="#ffd166","Targeted Pan-Cancer"="#ef476f"), name="Gene Panel")+
  mytheme+
  theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate x-axis labels 45 degrees
  )+
  xlab("Gene panels")+
  ylab("Predicted proportions")


plt_with_p_val=plt +
   stat_pvalue_manual(
     all_p_values %>% 
     dplyr::mutate(Deconvolution_tool=factor(Deconvolution_tool,levels = c("quanTIseq","EPIC","SPOTlight","SpatialDecon","CARD","RCTD","cell2location"))) %>% 
     mutate(p.adj.signif=ifelse(p.adj.signif=="****","**",p.adj.signif)) %>% 
     select(group1, group2, p.adj.signif, cell_type, Deconvolution_tool)%>% 
     dplyr::rename("Deconvolution_type"="Deconvolution_tool") %>% 
     mutate(y.position = case_when(
                cell_type=="B cell" & Deconvolution_type=="EPIC" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.4,
                cell_type=="B cell" & Deconvolution_type=="EPIC" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.50,
                cell_type=="B cell" & Deconvolution_type=="EPIC" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.6,
                cell_type=="T cell" & Deconvolution_type=="EPIC" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="EPIC" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="T cell" & Deconvolution_type=="EPIC" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                
                cell_type=="B cell" & Deconvolution_type=="SpatialDecon" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.3,
                cell_type=="B cell" & Deconvolution_type=="SpatialDecon" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.4,
                cell_type=="B cell" & Deconvolution_type=="SpatialDecon" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.5,
                cell_type=="T cell" & Deconvolution_type=="SpatialDecon" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.3,
                cell_type=="T cell" & Deconvolution_type=="SpatialDecon" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.4,
                cell_type=="T cell" & Deconvolution_type=="SpatialDecon" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.5,
                
                cell_type=="B cell" & Deconvolution_type=="quanTIseq" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="B cell" & Deconvolution_type=="quanTIseq" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="B cell" & Deconvolution_type=="quanTIseq" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                cell_type=="T cell" & Deconvolution_type=="quanTIseq" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="quanTIseq" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="T cell" & Deconvolution_type=="quanTIseq" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                
                cell_type=="B cell" & Deconvolution_type=="SPOTlight" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="B cell" & Deconvolution_type=="SPOTlight" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="B cell" & Deconvolution_type=="SPOTlight" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                cell_type=="T cell" & Deconvolution_type=="SPOTlight" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="SPOTlight" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="T cell" & Deconvolution_type=="SPOTlight" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                
                cell_type=="B cell" & Deconvolution_type=="RCTD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="B cell" & Deconvolution_type=="RCTD" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="B cell" & Deconvolution_type=="RCTD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                cell_type=="T cell" & Deconvolution_type=="RCTD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="RCTD" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="T cell" & Deconvolution_type=="RCTD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                
                cell_type=="B cell" & Deconvolution_type=="cell2location" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.5,
                cell_type=="B cell" & Deconvolution_type=="cell2location" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.6,
                cell_type=="B cell" & Deconvolution_type=="cell2location" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="cell2location" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.5,
                cell_type=="T cell" & Deconvolution_type=="cell2location" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.6,
                cell_type=="T cell" & Deconvolution_type=="cell2location" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.7,
                
                cell_type=="B cell" & Deconvolution_type=="CARD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="B cell" & Deconvolution_type=="CARD" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="B cell" & Deconvolution_type=="CARD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                cell_type=="T cell" & Deconvolution_type=="CARD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan-Cancer" ~ 0.7,
                cell_type=="T cell" & Deconvolution_type=="CARD" & group1=="Targeted Immunology" & group2=="Targeted Pan-Cancer" ~ 0.8,
                cell_type=="T cell" & Deconvolution_type=="CARD" & group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 0.9,
                          
                          # group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Pan Cancer" ~ 0.8,
                          # group1=="Targeted Immunology" & group2=="Targeted Pan Cancer" ~ 0.9,
                          # group1=="10x Visium \nWTA Probe-set" & group2=="Targeted Immunology" ~ 1
                        )),  # or assign real y-positions
     label = "p.adj.signif",
     xmin = "group1",
     xmax = "group2",
     y.position = "y.position",
     tip.length = 0.03,
     inherit.aes = FALSE
   )
```


```{r}
all_p_values %>% 
  filter(p.adj.signif =="****") %>% 
  pull(p.adj) %>% 
  min
```


```{r}
ggsave(filename = "../manuscript/figs/Ovarian_cancer_deconvolution_v4.png", plot = plt_with_p_val, width = 16, height = 8, units = "in")
```

```{r}
saveRDS(plt_with_p_val,file = "../manuscript/figs/Ovarian_cancer_deconvolution_v4.RDS")
```

```{r}
library(ggpubr)
ovarian_cancer_corplot=res_for_plots %>% 
  filter(Gene_panel !="Targeted Pan-Cancer") %>% 
  pivot_wider( names_from = Gene_panel,
  values_from = Deconvolution_proportions) %>% 
  janitor::clean_names() %>% 
  ggplot(aes(x= x10x_visium_wta_probe_set,y= targeted_immunology, color=cell_type))+
  geom_point(aes(color=cell_type))+
  #stat_cor(method = "pearson",size=4, aes(label = ifelse(is.na(..r..), NA, ..r.label..)), label.x.npc = "center", label.y.npc = "bottom")+
  facet_wrap(~deconvolution_type, scales = "free", nrow = 1)+
#  ggpubr:: stat_cor(method = "pearson")+
         scale_color_manual (values = c ( "B cell"  =  "#8DD3C7" ,
                                          "T cell"  =  "#FDB462"), name="Cell Type")+
  xlab("Proportions predicted on \n 10x Visium WTA Probe-set Panel")+
  ylab("Proportions predicted on \n Targeted Immunology Panel")+
  # geom_segment(aes(x = min(x10x_visium_wta_probe_set), y = min(targeted_immunology),
  #                  xend = max(x10x_visium_wta_probe_set), yend = max(targeted_immunology)),
  #              color = "black", linetype = "dotted", size = 1)+
  geom_abline(intercept = 0, slope = 1,
              color = "red", linetype = "dotted", size = 1)+
  mytheme+
  coord_cartesian(xlim = c(0, NA), ylim = c(0, NA))


ggsave(filename = "../manuscript/figs/Ovarian_cancer_deconvolution_corplot.png", plot = ovarian_cancer_corplot, width = 8, height = 8, units = "in")
saveRDS(ovarian_cancer_corplot,file = "../manuscript/figs/Ovarian_cancer_deconvolution_corplot.RDS")
```
