---
title: "analysis_v0.3"
author: "Aakanksha Singh"
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE,warning=FALSE}
source("./functions.R")
```

# Bootstraped data for PBMC
```{r}
# Pseudobulks generated from Chromium 10X
bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_pseudobulks_03072024.RData")
bootstraped_data_cell_counts=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_cell_proportions_03072024.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))


bootstraped_data_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_for_epic_pseudobulks_13102025.RData")
bootstraped_data_cell_counts_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_for_epic_cell_proportions_13102025.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))

# Signature Matrix
signature_reference <- readRDS("../intermediate_data/processed_sces/pbmc8k.rds")

cell_types=c("B cell","T cell","Monocyte","NK cell")
analysis_type="PBMC"


# bootstraped_data_cell_counts%>%
#       select(contains("boot")) %>%
#       select(contains("actual_values")) %>%
#       colSums() %>%
#       max()
```

# Bootstraped data for AML
```{r}
# Pseudobulks generated from Chromium 10X
bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_pseudobulks_03072024.RData")
bootstraped_data_cell_counts=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_cell_proportions_03072024.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))

bootstraped_data_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_for_epic_pseudobulks_13102025.RData")
bootstraped_data_cell_counts_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_for_epic_cell_proportions_13102025.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))

# Signature Matrix
signature_reference <- readRDS("../intermediate_data/processed_sces/AML0210X.rds")
analysis_type="AML"
cell_types=c("B cell","T cell","Monocyte","NK cell")

# bootstraped_data_cell_counts%>%
#       select(contains("boot")) %>%
#       select(contains("actual_values")) %>%
#       colSums() %>%
#       mean()
# 
# colnames(bootstraped_data)
```

```{r}
length(unique(bootstraped_data$HUGO))
```

PART 1: Gene Panel
## Gene Panel Variables
```{r}
# List of the gene panels to be tested
all_genes= bootstraped_data %>% 
           dplyr::select("HUGO") %>% 
           dplyr::rename("V1"="HUGO")

BD_genes <- read.delim("../Data/gene_panels/cDNA_BD_Kit.txt", header = FALSE) 
tenX_genes <-read.delim("../Data/gene_panels/Visium_gene_list.txt", header = FALSE)
nanostring_genes <- read_xlsx("../Data/gene_panels/GeoMx-Human-Whole-Transcriptome-Atlas-Probe-List_v0.1.xlsx",skip = 1,
                              sheet="Probe Details") %>% dplyr::rename("V1"="Formal Gene Name")
xenium_genes <- read_csv("../Data/gene_panels/Xenium_hIO_v1_metadata.csv") %>% 
                dplyr::rename("V1"="Gene")

targeted_human_immunology_panel=read_csv("../Data/gene_panels/Targeted_immunology_v1.0_GRCh38-2020-A.target_panel.csv", skip = 5) %>% 
                                dplyr::select(bait_id) %>%
                                separate(col = bait_id, into = c("ENSEMBL_id","V1","Probe_number"), sep = "\\|") %>% 
                                dplyr::select(V1) %>% 
                                distinct()

targeted_pan_cancer_panel=read_csv("../Data/gene_panels/Targeted_Visium_Human_OvarianCancer_Pan_Cancer_target_panel.csv", skip = 5) %>% 
                                dplyr::select(bait_id) %>%
                                separate(col = bait_id, into = c("ENSEMBL_id","V1","Probe_number"), sep = "\\|") %>% 
                                dplyr::select(V1) %>% 
                                distinct()


# Input variables for benchmarking for gene panels
gene_panels= list("All detected \ngenes"=all_genes,"10x Visium \nWTA Probe-set"=tenX_genes,"Nanostring WTA"= nanostring_genes,"BD Rhapsody"= BD_genes,"Targeted \nImmunology"=targeted_human_immunology_panel,"Targeted \nPan-Cancer"=targeted_pan_cancer_panel,"Xenium \nImmuno-Oncology Panel"=xenium_genes)
cell_types=c("B cell","T cell","Monocyte","NK cell")
date="13102025"  
column_character_specifications_for_mcp=NA
```


```{r}
complete_gene_panel_benchmarking_list =list(names(gene_panels)) 
for (j in names(gene_panels)) 
  { 
    gene_list= gene_panels[[j]]
    gene_panel_benchmarking <-data.frame()
    
    # Filtering genes based on gene panels and normalizing according to TPM
    deconv_table=bootstraped_data %>%
                 dplyr::filter(HUGO %in% gene_list$V1 ) %>%
                 mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6))
    
    deconv_table_epic=bootstraped_data_epic %>%
                 dplyr::filter(HUGO %in% gene_list$V1 ) %>%
                 mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6))
    
    actual_cell_proportions= bootstraped_data_cell_counts
    actual_cell_proportions_epic= bootstraped_data_cell_counts_epic
    
    # Deconvolution
    result_df <- deconvolution_for_bootstrap_v4(deconv_table,
                                                deconv_table_epic,
                                                signature_reference, 
                                                actual_cell_proportions,
                                                actual_cell_proportions_epic,
                                                column_character_specifications_for_mcp=NA)
    
    # Wrangling_data
    comp_gene_panel_res= result_df %>%
          pivot_longer(cols = -c(deconv_type, cell_type),
                      names_to = c("Dataset", ".value"),
                      names_pattern = "^(.*_boot\\d+)\\.(Raw|actual_values|actual_frac)$") %>% 
         dplyr::rename("Deconvolution_fraction"="Raw") %>% 
         dplyr::mutate("Gene_panel"=j)
    
    # Adding to list
    complete_gene_panel_benchmarking_list[[j]] = comp_gene_panel_res
}

```

# Data Wrangling
```{r}
gene_panel_res <- rbind(complete_gene_panel_benchmarking_list$`All detected \ngenes`,
          complete_gene_panel_benchmarking_list$`10x Visium \nWTA Probe-set`,
          complete_gene_panel_benchmarking_list$`Nanostring WTA`,
          complete_gene_panel_benchmarking_list$`Targeted \nPan-Cancer`,
          complete_gene_panel_benchmarking_list$`Targeted \nImmunology`,
          complete_gene_panel_benchmarking_list$`BD Rhapsody`,
          complete_gene_panel_benchmarking_list$`Xenium \nImmuno-Oncology Panel`) %>% 
          mutate(deconv_type = ifelse(deconv_type=="SpatialDecon (TME)\n cells unknown","SpatialDecon",deconv_type)) %>% 
          mutate(deconv_type=factor(deconv_type, levels=c("quanTIseq",
                                                          "EPIC",
                                                          "MCPcounter*",
                                                          "SPOTlight",
                                                          "SpatialDecon"))) %>% 
         mutate(Gene_panel=factor(Gene_panel, levels=c("All detected \ngenes","10x Visium \nWTA Probe-set","Nanostring WTA","Targeted \nPan-Cancer", "Targeted \nImmunology","BD Rhapsody","Xenium \nImmuno-Oncology Panel")))

saveRDS(gene_panel_res, file = paste0("../Results/Gene_panel/",analysis_type,"_gene_panel_",date,".RDS"))    
```

PART 2: Normalisation
# Normalisation
```{r}
date="13102025"
normalization_types=c("Raw","TPM normalized","Quantile normalized","Q3 normalized")
complete_normalization_benchmarking_list =list(normalization_types)
column_character_specifications_for_mcp=NA

for (j in normalization_types) 
  {
    deconv_mat <- bootstraped_data %>% 
                   column_to_rownames(var = "HUGO") %>% 
                   as.matrix()
    deconv_mat= deconv_mat[complete.cases(deconv_mat), ]
    
    deconv_mat_epic <- bootstraped_data_epic %>% 
                   column_to_rownames(var = "HUGO") %>% 
                   as.matrix()
    
    deconv_mat_epic= deconv_mat_epic[complete.cases(deconv_mat_epic), ]
    
    # Differnt normalisations
    # No normalization
    if(j=="Raw")
    {
      deconv_df <- deconv_mat %>% 
                   as.data.frame() %>% 
                   rownames_to_column(var="HUGO") 
                   #rename_with(~sub(".Raw$", ".norm", .), ends_with(".Raw"))
      deconv_df_epic <- deconv_mat_epic %>% 
                   as.data.frame() %>% 
                   rownames_to_column(var="HUGO") 
    }
    
    # TPM normalisation
    if(j=="TPM normalized")
    {
      deconv_df <- bootstraped_data %>% 
                   mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6)) 
                   #rename_with(~sub(".Raw$", ".norm", .), ends_with(".Raw"))
      
      deconv_df_epic <- bootstraped_data_epic %>% 
                   mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6)) 
    }
    
    # Quantile normalisation 
    if(j=="Quantile normalized")
    {
      deconv_df <- normalize.quantiles(deconv_mat,keep.names=TRUE) %>% 
                             as.data.frame() %>% 
                             rownames_to_column(var="HUGO") 
                             #rename_with(~sub(".Raw$", ".norm", .), ends_with(".Raw"))
      
      deconv_df_epic <- normalize.quantiles(deconv_mat_epic,keep.names=TRUE) %>% 
                             as.data.frame() %>% 
                             rownames_to_column(var="HUGO") 
    }
    
    # Q3 normalisation
    if(j=="Q3 normalized")
    {
       q3_values <- apply(deconv_mat, 2, function(x) quantile(x, 0.75))
       q3_geometric_mean=exp(mean(log(q3_values)))
       mat_q3_norm= sweep(deconv_mat, 2, q3_values, FUN = "/") * q3_geometric_mean
      
      deconv_df<-     mat_q3_norm %>% 
                      #(deconv_mat / Q3_values) %>% 
                       as.data.frame() %>% 
                       rownames_to_column(var="HUGO") 
                       #rename_with(~sub(".Raw$", ".norm", .), ends_with(".Raw"))
      
      q3_values_epic <- apply(deconv_mat_epic, 2, function(x) quantile(x, 0.75))
      q3_geometric_mean_epic=exp(mean(log(q3_values_epic)))
      mat_q3_norm_epic = sweep(deconv_mat_epic, 2, q3_values_epic, FUN = "/") * q3_geometric_mean_epic
      
      deconv_df_epic<-  mat_q3_norm_epic %>% 
                      #(deconv_mat / Q3_values) %>% 
                       as.data.frame() %>% 
                       rownames_to_column(var="HUGO") 
    
    }
    
    actual_cell_proportions= bootstraped_data_cell_counts
    
    # Deconvolution
    result_df <- deconvolution_for_bootstrap_v4(deconv_df, 
                                                deconv_df_epic,
                                                signature_reference,
                                                actual_cell_proportions, 
                                                actual_cell_proportions_epic, 
                                                column_character_specifications_for_mcp=NA)
    
    # Wrangling_data
    comp_normalisation_res= result_df %>%
          pivot_longer(cols = -c(deconv_type, cell_type),
                      names_to = c("Dataset", ".value"),
                      names_pattern = "^(.*_boot\\d+)\\.(Raw|actual_values|actual_frac)$") %>% 
         dplyr::rename("Deconvolution_fraction"="Raw") %>% 
         dplyr::mutate("Normalisation"=j)
    
    # Adding to list
    complete_normalization_benchmarking_list[[j]] = comp_normalisation_res
  }
```

```{r}
normalisation_res <- rbind(complete_normalization_benchmarking_list$Raw,
                           complete_normalization_benchmarking_list$`TPM normalized`,
                           complete_normalization_benchmarking_list$`Quantile normalized`,
                           complete_normalization_benchmarking_list$`Q3 normalized`) %>% 
                    mutate(deconv_type = ifelse(deconv_type=="SpatialDecon (TME)\n cells unknown","SpatialDecon",deconv_type)) %>% 
                    mutate(deconv_type=factor(deconv_type, levels=c("quanTIseq",
                                                                  "EPIC",
                                                                  "MCPcounter*",
                                                                  "SPOTlight",
                                                                  "SpatialDecon"))) %>% 
                    mutate(Normalisation=factor(Normalisation))

save(normalisation_res, file = paste0("../Results/Normalisation/",analysis_type,"_normalisation_",date,".RData"))     
```

PART 3: Signature Matrices
# Signature Matrices
```{r}
# Reading all the signature matrices
lm22= read_delim("../Data/Signature_matrices/LM22_signature_matrix.txt") %>% 
      column_to_rownames(var = "Gene symbol") %>% as.matrix()

til10 = read_xlsx("../Data/Signature_matrices/TIL10_signature_matrix.xlsx", sheet = "Signature") %>% 
        mutate_at(vars(-GeneSymbol), as.numeric) %>% 
        column_to_rownames(var="GeneSymbol") %>% as.matrix()

immunostates= read_xlsx("../Data/Signature_matrices/Immunostates_blood_cell_matrix.xlsx") %>% 
              janitor::row_to_names(2) %>% 
              mutate_at(vars(-Gene), as.numeric) %>% 
              column_to_rownames(var= "Gene") %>% as.matrix()

safetme= safeTME %>% 
         as.data.frame() %>% 
         rownames_to_column(var = "Gene_symbol")

signature_matrices=list("LM22"=lm22,
                        "TIL10"=til10,
                        "immunostates"=immunostates,
                        "safeTME"=safetme)
```

```{r}
complete_signature_matrix_benchmarking_list =list(names(signature_matrices)) 

    
   signature_matrix_benchmarking_benchmarking <-data.frame()
    
    # Filtering genes based on gene panels and normalising according to TPM
    deconv_table=bootstraped_data %>% 
                 mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6)) %>% 
                 rename_with(~sub(".Raw$", ".norm", .), ends_with(".Raw"))
    actual_cell_proportions= bootstraped_data_cell_counts
    
    # Deconvolution
    result_df <- signature_matrix_bootstrapping(deconv_table,cell_types, signature_reference, actual_cell_proportions)
    
    # Wrangling_data
    comp_signature_matrix_res= result_df %>%
          pivot_longer(cols = -c(deconv_type, cell_type),
                      names_to = c("Dataset", ".value"),
                      names_pattern = "^(.*_boot\\d+)\\.(norm|actual_values|actual_frac)$") %>% 
         dplyr::rename("Deconvolution_fraction"="norm") 
    
save(comp_signature_matrix_res, file = paste0("../Results/Signature_Matrix/",analysis_type,"_signature_matrix.RData"))   
```

# Spot Size
```{r}
# Pseudobulks generated from Chromium 10X
bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_pseudobulks_spot_size_01102025.RData")
bootstraped_data_cell_counts=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_cell_proportions_spot_size_01102025.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))

bootstraped_data_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_for_epic_pseudobulks_spot_size_13102025.RData")
bootstraped_data_cell_counts_epic=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_for_epic_cell_proportions_spot_size_13102025.RData") %>%
                             dplyr::rename_with(~str_replace(., "_boot$", ""), ends_with("_boot"))

# Signature Matrix
signature_reference <- readRDS("../intermediate_data/processed_sces/pbmc8k.rds")
# signature_reference_ss <- readRDS("../intermediate_data/processed_sces/SS2_PBMC_2.rds")
cell_types=c("B cell","T cell","Monocyte","NK cell")
analysis_type="PBMC"
date="13102025"
column_character_specifications_for_mcp=c(".4",".125",".1000")
```

```{r}

    # Filtering genes based on gene panels and normalising according to TPM
    deconv_table=bootstraped_data %>%
                 #dplyr::filter(HUGO %in% gene_list$V1 ) %>%
                 mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6))

   deconv_table_epic=bootstraped_data_epic %>%
                 #dplyr::filter(HUGO %in% gene_list$V1 ) %>%
                 mutate(across(-1, ~ (.x / sum(.x, na.rm = TRUE)) * 1e6))
    
    # For real data uncomment the line below
    # deconv_table= bootstraped_data %>%
    #               rename_with(~ if_else(startsWith(., "Sample"), paste0(., ".Raw"), .))
    
    actual_cell_proportions= bootstraped_data_cell_counts
    actual_cell_proportions_epic= bootstraped_data_cell_counts_epic
    
    # Deconvolution
    result_df <- deconvolution_for_bootstrap_v4(deconv_table, 
                                                deconv_tabe_epic,
                                                signature_reference, 
                                                actual_cell_proportions,
                                                actual_cell_proportions_epic,
                                                column_character_specifications_for_mcp)
    
    # Wrangling_data
    spot_size_res= result_df %>%
          pivot_longer(cols = -c(deconv_type, cell_type),
                      names_to = c("Dataset", ".value"),
                      names_pattern = "^(.*_boot\\d+)\\.(Raw|actual_values|actual_frac)$") %>% 
                      # for real data comment out the names_pattern line above and uncomment the line below
                      # names_sep = "\\.") %>% 
         dplyr::rename("Deconvolution_fraction"="Raw") %>% 
         dplyr::mutate("Max_spot_size"=sub(".*\\.(\\d+)_.*", "\\1", Dataset)) %>% 
         dplyr::filter(!deconv_type %in% c("SpatialDecon (Custom)\n cells known","SpatialDecon (TME)\n cells known")) %>% 
                  mutate(deconv_type = ifelse(deconv_type=="SpatialDecon (Custom)\n cells unknown","SpatialDecon \n custom signature",deconv_type),
                         deconv_type = ifelse(deconv_type=="SpatialDecon (TME)\n cells unknown","SpatialDecon \n default signature",deconv_type)) %>% 
                  mutate(deconv_type=factor(deconv_type, levels=c("quanTIseq",
                                                                  "EPIC",
                                                                  "MCPcounter*",
                                                                  "SPOTlight",
                                                                  "SpatialDecon \n default signature",
                                                                  "SpatialDecon \n custom signature"))) %>% 
      mutate(Max_spot_size=paste("Max",as.integer(Max_spot_size)*4,"cells \n in Sample/Spot")) %>% 
      mutate(Max_spot_size=case_when(Max_spot_size=="Max 16 cells \n in Sample/Spot"~"6-12 cells \n in Sample/Spot",
                                     Max_spot_size=="Max 500 cells \n in Sample/Spot"~"75-496 cells \n in Sample/Spot",
                                     Max_spot_size=="Max 4000 cells \n in Sample/Spot"~"600-3996 cells \n in Sample/Spot")) %>% 
      mutate(Max_spot_size= factor(Max_spot_size,
                                   levels=c("600-3996 cells \n in Sample/Spot","75-496 cells \n in Sample/Spot","6-12 cells \n in Sample/Spot")))

saveRDS(spot_size_res, file = paste0("../Results/Max_spot_size/",analysis_type,"_spot_size_",date,".RDS"))     

```


