---
title: "testing CARD, RCTD and cell2Location"
output: html_document
date: "2026-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Testing deconvolution with CARD
```{r}
source("./0_functions.R")
```

# Installing zellkonverter
```{r}
library("zellkonverter")
library(basilisk)
library(scRNAseq)
library(tidyverse)
library(SpatialExperiment)
```

#Converting signature sce to anndata (pbmc_data)
```{r}
#PBMC
signature_reference <- readRDS("../intermediate_data/processed_sces/pbmc8k.rds")
signature_reference$cell_type=signature_reference$cell # creating col names cell_type
colnames(signature_reference)= signature_reference$Barcode #creating colnames
signature_reference <- signature_reference[!duplicated(rownames(signature_reference)), ] # removing deuplicate rows
colData(signature_reference)$Tissue_status <- NULL # python couldn't handle the NA values
writeH5AD(signature_reference, file = "../intermediate_data/processed_sces/pbmc8k.h5ad")

#AML
signature_reference <- readRDS("../intermediate_data/processed_sces/AML0210X.rds")
signature_reference$cell_type=signature_reference$cell # creating col names cell_type
colnames(signature_reference)= signature_reference$Barcode #creating colnames
signature_reference <- signature_reference[!duplicated(rownames(signature_reference)), ] # removing deuplicate rows
colData(signature_reference)$Tissue_status <- NULL # python couldn't handle the NA values
writeH5AD(signature_reference, file = "../intermediate_data/processed_sces/AML0210X.h5ad")

#PBMC20k (Sequencing Depth)
signature_reference <- readRDS("../intermediate_data/processed_sces/sequencing_depth/PBMC20k_1_cell_ranger.rds")
signature_reference$cell_type=signature_reference$cell # creating col names cell_type
signature_reference$Barcode=colnames(signature_reference) #creating colnames
signature_reference <- signature_reference[!duplicated(rownames(signature_reference)), ] # removing deuplicate rows
colData(signature_reference)$Tissue_status <- NULL # python couldn't handle the NA values
colData(signature_reference)$Sample <- sub(".*_", "", signature_reference$Barcode)
writeH5AD(signature_reference, file = "../intermediate_data/processed_sces/sequencing_depth/PBMC20k_1_cell_ranger.h5ad")


#Bone Marrow20k (Sequencing Depth)
signature_reference <- readRDS("../intermediate_data/processed_sces/sequencing_depth/bone_marrow_20k_1_cell_ranger.rds")
signature_reference$cell_type=signature_reference$cell # creating col names cell_type
signature_reference$Barcode=colnames(signature_reference) #creating colnames
signature_reference <- signature_reference[!duplicated(rownames(signature_reference)), ] # removing deuplicate rows
colData(signature_reference)$Tissue_status <- NULL # python couldn't handle the NA values
colData(signature_reference)$Sample <- sub(".*_", "", signature_reference$Barcode)
writeH5AD(signature_reference, file = "../intermediate_data/processed_sces/sequencing_depth/bone_marrow_20k_1_cell_ranger.h5ad")


# Glioma
load("~/mnt_TLS_project/Single_cell_reference_from_brain/updated_glioma_sce")
glioma_sce_annotation= as.data.frame(colData(updated_glioma_sce)) %>%
                               mutate("cell_name" = rownames(colData(updated_glioma_sce))) %>%
                               mutate(new_cell_type= as.character(annotation_level_2)) %>%
                               mutate(cell_type= as.character(cell_type)) %>%
                               mutate(new_cell_type= ifelse(new_cell_type=="Lymphoid",cell_type,new_cell_type)) %>%
                               mutate(new_cell_type= ifelse(new_cell_type=="Vascular",cell_type,new_cell_type)) %>%
                               mutate(new_cell_type= ifelse(annotation_level_3=="DC","Dendritic cell",new_cell_type))

glioma_sce_annotation$Barcode=rownames(glioma_sce_annotation)
glioma_sce_annotation$sample=glioma_sce_annotation$author
glioma_sce_annotation$cell_type=glioma_sce_annotation$new_cell_type
colData(updated_glioma_sce)=glioma_sce_annotation %>% DataFrame()

updated_glioma_sce <- updated_glioma_sce[!duplicated(rownames(updated_glioma_sce)), ] # removing deuplicate rows
colData(updated_glioma_sce)$Tissue_status <- "glioma"
write_rds(updated_glioma_sce,file = "~/mnt_AG_Imkeller/group_members/asingh/Benchmarking_deconvolution_update/Benchmarking_deconvolution_github/intermediate_data/processed_sces/glioma_sce.rds")


library(zellkonverter)
writeH5AD(updated_glioma_sce, file = "~/mnt_AG_Imkeller/group_members/asingh/Benchmarking_deconvolution_update/Benchmarking_deconvolution_github/intermediate_data/processed_sces/glioma_sce.h5ad")

```

# Converting pseudobulk data anndata
```{r}
# PBMC
#bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_pseudobulks_03072024.RData")
bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_for_epic_pseudobulks_13102025.RData")

set.seed(2354)
bootstraped_metadata=data.frame("Sample"=colnames(bootstraped_data[2:ncol(bootstraped_data)])) %>% 
  mutate(dataset=as.factor(str_extract(Sample, "^[^_]+")),
         Bootstrap=str_extract(Sample, "(?<=_)[^.]+"), # Extracting bootn string
         Bootstrap=str_extract(Bootstrap, "[0-9]+"), # Extracting n (the bootrsap number)
         x=sample(1L:nrow(.), n(), replace = FALSE), 
         y=sample(1L:nrow(.), n(), replace = FALSE)) %>% 
         column_to_rownames(var = "Sample") 
  
bootstraped_data_matrix=bootstraped_data %>% 
                 column_to_rownames(var="HUGO") %>% 
                 as.matrix()

spe=SpatialExperiment(assay = list(counts = bootstraped_data_matrix),
                        spatialCoords  = as.matrix(bootstraped_metadata %>% select(x,y)),
                        colData=bootstraped_metadata)

#writeH5AD(spe, file = "../intermediate_data/bootstraped_pseudobulks/pbmc_pseudobulks.h5ad")
writeH5AD(spe, file = "../intermediate_data/bootstraped_pseudobulks/pbmc_pseudobulks_for_epic.h5ad")

#AML
#bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_pseudobulks_03072024.RData")
bootstraped_data=readRDS("../intermediate_data/bootstraped_pseudobulks/aml_10x_for_epic_pseudobulks_13102025.RData")
set.seed(2354)
bootstraped_metadata=data.frame("Sample"=colnames(bootstraped_data[2:ncol(bootstraped_data)])) %>% 
  mutate(dataset=as.factor(str_extract(Sample, "^[^_]+")),
         Bootstrap=str_extract(Sample, "(?<=_)[^.]+"), # Extracting bootn string
         Bootstrap=str_extract(Bootstrap, "[0-9]+"), # Extracting n (the bootrsap number)
         x=sample(1L:nrow(.), n(), replace = FALSE), 
         y=sample(1L:nrow(.), n(), replace = FALSE)) %>% 
         column_to_rownames(var = "Sample") 
  
bootstraped_data_matrix=bootstraped_data %>% 
                 column_to_rownames(var="HUGO") %>% 
                 as.matrix()

spe=SpatialExperiment(assay = list(counts = bootstraped_data_matrix),
                        spatialCoords  = as.matrix(bootstraped_metadata %>% select(x,y)),
                        colData=bootstraped_metadata)

#writeH5AD(spe, file = "../intermediate_data/bootstraped_pseudobulks/aml_pseudobulks.h5ad")
writeH5AD(spe, file = "../intermediate_data/bootstraped_pseudobulks/aml_pseudobulks_for_epic.h5ad")
```

# Converting Human ovarian cancer data
```{r}
sce <- readH5AD("../Data/ovarian_cancer_scRNAseq/584027d5-32d7-4696-9424-f61134ff2aa7.h5ad", reader = "R")
```


