---
title: "NS_v_Visium_4_samples"
output: html_document
date: "2025-04-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(dplyr)
library(tidyr)
library(SpatialExperiment)
library(Seurat)
library(ggplot2)
library(SpatialDecon)
library(RColorBrewer)
library(ggpubr)
library(immunedeconv)
library(DropletUtils)
library(tidyverse)
library(ggpubr)
```


```{r}
setClassUnion("ExpData", c("matrix", "SummarizedExperiment"))
```

```{r}
source("./functions.R")
```

# The raw data used in this scipt will be made available upon request upon authors. The results of this script are provided.
# Important note: certain sections of the script that contain patient identifiers are redacted.

# Nanostring data
```{r}
nanostring<- read.csv("~/PATH/Results/raw_data/All_Data_WTA_probe_QC.csv",header = TRUE)

nanostring_df=nanostring[,c("TargetName","GBM.003.Full.ROI","GBM.002.Full.ROI","GBM.007.Full.ROI","GBM.004.Full.ROI","GBM.006.Full.ROI","GBM.014.Full.ROI","BM.002.Full.ROI","BM.001.Full.ROI","BM.003.Full.ROI","BM.006.Full.ROI","BM.004.Full.ROI","BM.005.Full.ROI")] %>% 
dplyr::rename("Redacted_Tumor_GBM_003"="GBM.003.Full.ROI",
              "Redacted_TLS_GBM_002"="GBM.002.Full.ROI",
              "Redacted_Tumor_GBM_007"="GBM.007.Full.ROI",
              "Redacted_TLS_GBM_004"="GBM.004.Full.ROI",
              "Redacted_TLS_GBM_006"="GBM.006.Full.ROI",
              "Redacted_TLS_GBM_014"="GBM.014.Full.ROI",
              "Redacted_Tumor_BM_002"="BM.002.Full.ROI",
              "Redacted_TLS_BM_002"="BM.001.Full.ROI",
              "Redacted_TLS_BM_003"="BM.003.Full.ROI",
              "Redacted_Tumor_BM.006"="BM.006.Full.ROI",
              "Redacted_TLS_BM.004"="BM.004.Full.ROI",
              "Redacted_TLS_BM.005"="BM.005.Full.ROI")

```

# Visium Data
```{r}
visium_samples_reading<-function(file_folder,annotated_file,E_nummer)
{
      colnames(annotated_file)=c("Barcode","TLS")
      output_matrix <-read10xCounts(paste0(file_folder,"filtered_feature_bc_matrix" ))
    
      cdata=colData(output_matrix) %>% 
            as.data.frame() %>% 
            left_join(annotated_file,by=c("Barcode"="Barcode")) %>% 
            mutate(E_nummer=E_nummer) %>% 
            mutate(TLS=ifelse(is.na(TLS)==FALSE & TLS != "Tumor_only","TLS",TLS)) %>% 
            mutate(Spotname=paste(E_nummer,TLS,Barcode, sep = "_")) %>% 
            DataFrame()
      
      colData(output_matrix)=cdata
      output_matrix_filtered=output_matrix[,is.na(colData(output_matrix)$TLS)==FALSE]
      colnames(output_matrix_filtered)=colData(output_matrix_filtered)$Spotname
      return(output_matrix_filtered)
}

#Sample 1
sample1<-"~/PATH/Visium02_S1/outs/"
sample1_annotated_file <- read.csv(paste0(sample1,"Visium02_S1_TLSannotation_loupe.csv"), header = TRUE)

# Sample2
sample2<-"~/PATH/Visium02_S2/outs/"
sample2_annotated_file <-read.csv(paste0(sample2,"Visium02_S2_TLSannotation_loupe.csv"), header = TRUE)

# Sample3
sample3<-"~/PATH/Visium02_S3/outs/"
sample3_annotated_file <-read.csv(paste0(sample3,"Visium02_S3_TLSannotation_loupe.csv"), header = TRUE)

#Sample4
sample4<-"~/PATH/Visium02_S4/outs/"
sample4_annotated_file <-read.csv(paste0(sample4,"Visium02_S4_TLSannotation_loupe.csv"), header = TRUE)

visium_obj= cbind(visium_samples_reading(sample1,sample1_annotated_file,"Redacted"),
                 visium_samples_reading(sample2,sample2_annotated_file,"Redacted"),
                 visium_samples_reading(sample3,sample3_annotated_file,"Redacted"),
                 visium_samples_reading(sample4,sample4_annotated_file,"Redacted"))

rownames(visium_obj)=rowData(visium_obj)$Symbol

visium_mat=as.matrix(assay(visium_obj))
```

# Deconvolution
```{r}
deconvolute_real_data=function(mat,bg)
{
# TPM like normalisaion
mat_tpm_like= apply(mat, 2, function(x) x * 1000000 / sum(x))

# Calculate Q3 for each column
q3_values <- apply(mat, 2, function(x) quantile(x, 0.75))
q3_geometric_mean=exp(mean(log(q3_values)))
mat_q3_norm= sweep(mat, 2, q3_values, FUN = "/") * q3_geometric_mean


quntiseq_res <- deconvolute(mat_tpm_like, "quantiseq",tumor = TRUE) %>% 
                mutate(cell_type= ifelse(grepl("T cell",cell_type)==TRUE,"T cell",cell_type)) %>% 
                dplyr::group_by(cell_type) %>% 
                dplyr::summarise_if(is.numeric, sum) %>% 
                pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                mutate(Deconvolution_type="quanTIseq")


 mcp_counter_res <- deconvolute(mat_tpm_like, "mcp_counter",tumor = TRUE) %>% 
                    min_max_normalisation_for_mcp(.,"E_","") %>% 
                    #mutate(across(contains("E_"), ~./sum(.))) %>% 
                    mutate(cell_type= ifelse(grepl("T cell",cell_type)==TRUE,"T cell",cell_type)) %>% 
                    dplyr::group_by(cell_type) %>% 
                    dplyr::summarise_if(is.numeric, sum) %>% 
                    pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                    mutate(Deconvolution_type="MCPcounter")

 epic_res <- deconvolute(mat_tpm_like, "epic",tumor = TRUE) %>% 
                mutate(cell_type= ifelse(grepl("T cell",cell_type)==TRUE,"T cell",cell_type)) %>%
                dplyr::group_by(cell_type) %>% 
                dplyr::summarise_if(is.numeric, sum) %>% 
                pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                mutate(Deconvolution_type="EPIC")
 
 spatial_decon_result= spatialdecon(mat_tpm_like,
                                 bg = bg,
                                 X = safeTME)

  spatial_decon_res=as.data.frame(spatial_decon_result$prop_of_all) %>% 
                     rownames_to_column(var="cell_type") %>% 
                     mutate(cell_type= ifelse(grepl("^T",cell_type)==TRUE,"T cell",cell_type)) %>%
                     mutate(cell_type= ifelse(grepl("^B.",cell_type)==TRUE,"B cell",cell_type)) %>% 
                     mutate(cell_type= ifelse(grepl("macrophages",cell_type)==TRUE,"Macrophage",cell_type)) %>% 
                     dplyr::group_by(cell_type) %>% 
                     dplyr::summarise_if(is.numeric, sum) %>% 
                     pivot_longer(cols = -cell_type, names_to = "Sample_name", values_to = "Deconvolution_proportions") %>% 
                     mutate(Deconvolution_type="SpatialDecon \ndefault signature")

  res_df= rbind(quntiseq_res,epic_res,mcp_counter_res,spatial_decon_res) %>% 
          mutate(cell_type = case_when(
          cell_type %in% c("Macrophage M1", "Macrophage M2") ~ "Macrophage",
          cell_type %in% c("monocytes.C", "monocytes.NC.I") ~ "Monocyte",
          cell_type == "NK" ~ "NK cell",
          cell_type == "endothelial.cells" ~ "Endothelial cell",
          cell_type == "fibroblasts" ~ "Fibroblast cell",
          cell_type %in% c("mDCs", "pDCs") ~ "Dendritic cell",
          cell_type == "mast" ~ "Mast cell",
          cell_type == "plasma" ~ "Plasma cell",
          cell_type == "neutrophils" ~ "Neutrophil",
          TRUE ~ cell_type )) %>% 
            dplyr::group_by(Deconvolution_type,Sample_name,cell_type) %>% 
                     dplyr::summarise_if(is.numeric, sum)
  return(res_df)
}
```

```{r}
# Selecting common genes to mitigate the impcat caused by having different gene panels
common_genes=intersect(nanostring_df$TargetName,rownames(visium_mat))

deconv_ns= deconvolute_real_data(as.matrix(nanostring_df %>% filter(TargetName %in% common_genes) %>% column_to_rownames(var="TargetName")),0.01)

#deconv_vi=res_df
deconv_vi=deconvolute_real_data(visium_mat[rownames(visium_mat) %in% common_genes,],0.1) 
```

```{r}
df=rbind(deconv_ns %>% mutate("Platform"="Nanostring GeoMx DSP"),
      deconv_vi %>% mutate("Platform"="10x Visium"))%>%
      mutate(Patient_id=str_sub(Sample_name,0,13))%>%
      mutate(Patient=case_when(Patient_id=="Redacted"~"P1",
                               Patient_id=="Redacted"~"P2",
                               Patient_id=="Redacted"~"P3",
                               Patient_id=="Redacted"~"P4"))%>%
    mutate(Deconvolution_type=ifelse(Deconvolution_type=="SpatialDecon \ndefault signature","SpatialDecon",Deconvolution_type),
           Deconvolution_type=ifelse(Deconvolution_type=="MCPcounter","MCPcounter*",Deconvolution_type))
```

```{r}
plt=df %>% 
mutate(Tissue_type=ifelse(str_sub(Sample_name,15,17)=="TLS","Immune_cell_rich","Tumor")) %>% 
filter(Tissue_type=="Immune_cell_rich") %>% 
#mutate(Patient=str_sub(Sample_name,1,13)) %>% 
filter(cell_type %in% c("B cell","T cell") ) %>% 
mutate(cell_type=factor(cell_type, levels=c("B cell","T cell","Monocyte","NK cell"))) %>% 
mutate(Deconvolution_type=factor(Deconvolution_type,levels=c("quanTIseq","EPIC","MCPcounter*","SpatialDecon")))%>%
ggplot(aes(x=Patient,y=Deconvolution_proportions, fill=Platform))+
       #geom_point(aes(color=cell_type, shape=), size=2) +
       geom_boxplot()+
       scale_fill_manual(values = c ("Nanostring GeoMx DSP"="#08415c",
                          "10x Visium"="#cc2936")) +
        # scale_shape_manual(values=c(0,1,2,3, 16, 17,11,4,8)) + theme(plot.title = element_text(hjust = 0.5)) +
        theme(axis.text.y   = element_text(size=14),
              axis.text.x   = element_text(size=14),
              axis.title.y  = element_text(size=14),
              axis.title.x  = element_text(size=14),
              panel.background = element_blank(),
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank(),
              axis.line = element_line(colour = "#C0C0C0"),
              panel.border = element_rect(colour = "#C0C0C0", fill=NA, size=1)) +
        ylab("Deconvolution proportions") +
        xlab("Patient") +
        ylim(0,1)+
        facet_grid(rows = vars(cell_type), cols = vars(Deconvolution_type))+
        stat_compare_means(aes(group=Platform),method = "t.test") +
        mytheme


ggsave(filename = "../manuscript/figs/Visium_vs_Nanostring_inhouse.png",plot = last_plot(), width = 10, height = 7, units = "in", dpi = 600)

write_rds(plt, file = "../manuscript/figs/Visium_vs_Nanostring_inhouse.RData")

```

