---
title: "Upset Plots"
author: "Aakanksha Singh"
date: "2025-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
source("./functions.R")
library(ComplexUpset)
library(preprocessCore)
```

#For Fig1
```{r}
# Upset Plots
all_genes= readRDS("../intermediate_data/bootstraped_pseudobulks/pbmc_10x_pseudobulks_03072024.RData") %>% 
           dplyr::select("HUGO") %>% 
           dplyr::mutate("All genes"= 1)
#write.csv(all_genes, file = "~/mnt_AG_Imkeller/group_members/asingh/Benchmarking_deconvolution/Data/gene_panels/all_genes_list.csv")
         

BD_genes <- read.delim("../Data/gene_panels/cDNA_BD_Kit.txt", header = FALSE) %>% dplyr::mutate("BD Rhapsody"=1)
tenX_genes <-read.delim("../Data/gene_panels/Visium_gene_list.txt", header = FALSE) %>% 
              dplyr::mutate("10x Visium WTA Probe-set"=1) %>% 
              dplyr::mutate(V1 = str_remove(V1, "\\..*"))

nanostring_genes <- read_xlsx("../Data/gene_panels/GeoMx-Human-Whole-Transcriptome-Atlas-Probe-List_v0.1.xlsx",skip = 1,
                              sheet="Probe Details") %>% dplyr::rename("V1"="Formal Gene Name") %>% 
                              dplyr::select(V1) %>% 
                              dplyr::mutate("Nanostring WTA"=1) %>% 
                              distinct()

targeted_human_immunology_panel=read_csv("../Data/gene_panels/Targeted_immunology_v1.0_GRCh38-2020-A.target_panel.csv", skip = 5) %>% 
                                dplyr::select(bait_id) %>%
                                separate(col = bait_id, into = c("ENSEMBL_id","V1","Probe_number"), sep = "\\|") %>% 
                                dplyr::select(V1) %>% 
                                distinct() %>% 
                                dplyr::mutate("Targeted Immunology"=1)

targeted_pan_cancer_panel=read_csv("../Data/gene_panels/Targeted_Visium_Human_OvarianCancer_Pan_Cancer_target_panel.csv", skip = 5) %>% 
                                dplyr::select(bait_id) %>%
                                separate(col = bait_id, into = c("ENSEMBL_id","V1","Probe_number"), sep = "\\|") %>% 
                                dplyr::select(V1) %>% 
                                distinct() %>% 
                                dplyr::mutate("Targeted Pan-Cancer"=1)

gene_df= all_genes %>% 
         left_join(BD_genes %>% distinct(),by=c("HUGO"="V1"), relationship="one-to-one",multiple="first") %>% 
         #left_join(xenium_genes, by=c("HUGO"="Gene"),relationship="one-to-one", multiple="first") %>% 
         left_join(nanostring_genes, by=c("HUGO"="V1"),relationship="one-to-one", multiple="first") %>% 
         left_join(tenX_genes %>% distinct(),by=c("HUGO"="V1"),relationship="one-to-one",multiple="first") %>% 
         left_join(targeted_human_immunology_panel %>% distinct(),by=c("HUGO"="V1"),relationship="one-to-one",multiple="first") %>% 
         left_join(targeted_pan_cancer_panel %>% distinct(),by=c("HUGO"="V1"),relationship="one-to-one",multiple="first") %>% 
         column_to_rownames(var="HUGO")

gene_df[is.na(gene_df)] <- 0 

upset_plot=ComplexUpset::upset(gene_df,intersect = colnames(gene_df), name='Gene Panel', width_ratio=0.3, min_size=10,
                               set_sizes=(upset_set_size(
                                          mapping=aes(y=..count../max(..count..)),)
        + scale_y_reverse(labels=scales::percent_format(suffix = ""), n.breaks=3)
        + ylab('% of genes')),
         themes=upset_modify_themes(
         list(
            'Intersection size'=theme(
                #axis.text=element_text(face='bold'),
                text = element_text(size = 15),
                axis.text=element_text( family = "Helvetica"),
                axis.title=element_text(face='bold',family = "Helvetica")
            ),
            'Set size'=theme(
                text = element_text(size = 15),
                axis.text=element_text(, family = "Helvetica"),
                axis.title=element_text(face='bold',family = "Helvetica")),
         theme(axis.text.x = element_text(angle = 90, hjust = 0.5)))
    ))

save(upset_plot,file = paste0("../manuscript/figs/gene_panel_upset_plot.RData"))
ggsave(plot = upset_plot,filename=paste0("../manuscript/figs/gene_panel_upset_plot3.png"),width = 10, height =5, units = "in", dpi = 600)
```

# upset plot fro signature matrix

```{r}
safetme=read_csv("../Data/Signature_matrices/safeTME.csv") %>% select("...1") %>% dplyr::rename(Gene= "...1") %>% mutate(SafeTME=1)
lm22=read_csv("../Data/Signature_matrices/LM22_signature_matrix.csv") %>% select("Gene.symbol") %>% dplyr::rename(Gene= "Gene.symbol") %>% mutate(LM22=1)
til10=read_xlsx("../Data/Signature_matrices/TIL10_signature_matrix.xlsx", sheet = "Signature") %>% select("GeneSymbol") %>% dplyr::rename(Gene= "GeneSymbol") %>% mutate(TIL10=1)
immunostates=read_xlsx("../Data/Signature_matrices/Immunostates_blood_cell_matrix.xlsx", skip = 2) %>% select("Gene") %>% dplyr::rename(Gene= "Gene") %>% mutate(Immunostates=1)

sig_df= full_join(safetme,lm22, by=c("Gene"="Gene")) %>% 
        full_join(til10, by=c("Gene"="Gene")) %>% 
        full_join(immunostates, by= c("Gene"="Gene")) %>% 
        column_to_rownames(var="Gene")


sig_df[is.na(sig_df)] <- 0 

upset_plot=ComplexUpset::upset(sig_df,intersect = colnames(sig_df), name='Signature Matrices', width_ratio=0.3,
                               set_sizes=(upset_set_size(
                                          mapping=aes(y=..count..),)
        + scale_y_reverse( n.breaks=6)
        + ylab('nb. of genes')),
        matrix=(
        intersection_matrix(geom=geom_point(shape='circle filled', size=3))
        + scale_color_manual(
            values=c('SafeTME'='#a559aa', 'LM22'='#f0c571', 'TIL10'='#082a54','Immunostates'='#e02b35'),
            guide=guide_legend(override.aes=list(shape='circle'))
        )
    ),
         themes=upset_modify_themes(
         list(
            'Intersection size'=theme(
                #axis.text=element_text(face='bold'),
                text = element_text(size = 10),
                axis.text=element_text( family = "Helvetica"),
                axis.title=element_text(face='bold',family = "Helvetica")
            ),
            'Set size'=theme(
                text = element_text(size = 10),
                axis.text=element_text(, family = "Helvetica"),
                axis.title=element_text(face='bold',family = "Helvetica")),
         theme(axis.text.x = element_text(angle = 90, hjust = 0.5)))
    ),
    queries=list(
        upset_query(set='SafeTME', fill='#a559aa'),
        upset_query(set='LM22', fill='#f0c571'),
        upset_query(set='TIL10', fill='#082a54'),
        upset_query(set='Immunostates', fill='#e02b35')
    ))


save(upset_plot,file = paste0("../manuscript/figs/signature_matrix_upset_plot.RData"))
ggsave(plot = upset_plot,filename=paste0("../manuscript/figs/signature_matrix_upset_plot.png"),width = 10, height =5, units = "in", dpi = 600)
```

